package interfaceGraphique;

public class InterfaceGraphique extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceGraphique
     */
    public InterfaceGraphique() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ams_btngrp_en_promotion = new javax.swing.ButtonGroup();
        panel_general = new javax.swing.JPanel();
        tpanel_onglets = new javax.swing.JTabbedPane();
        produits = new javax.swing.JPanel();
        panel_recherche = new javax.swing.JPanel();
        r_lbl_nom_produit = new javax.swing.JLabel();
        r_tf_nom_produit = new javax.swing.JTextField();
        r_lbl_categorie = new javax.swing.JLabel();
        javax.swing.JComboBox<String> r_cbb_categorie = new javax.swing.JComboBox<>();
        r_lbl_sous_cat = new javax.swing.JLabel();
        r_cbb_sous_cat = new javax.swing.JComboBox<>();
        r_btn_rechercher = new javax.swing.JButton();
        r_btn_effacer = new javax.swing.JButton();
        panel_p_ajout_modif_suppr = new javax.swing.JPanel();
        ams_lbl_id_produit = new javax.swing.JLabel();
        ams_tf_id_produit = new javax.swing.JTextField();
        ams_p_lbl_categorie = new javax.swing.JLabel();
        ams_cbb_categorie = new javax.swing.JComboBox<>();
        ams_p_lbl_sous_cat = new javax.swing.JLabel();
        ams_cbb_sous_cat = new javax.swing.JComboBox<>();
        ams_lbl_nom_produit = new javax.swing.JLabel();
        ams_tf_nom_produiit = new javax.swing.JTextField();
        ams_lbl_description = new javax.swing.JLabel();
        ams_scroll_description = new javax.swing.JScrollPane();
        ams_ta_description = new javax.swing.JTextArea();
        ams_lbl_prix = new javax.swing.JLabel();
        ams_tf_prix = new javax.swing.JTextField();
        ams_lbl_en_promotion = new javax.swing.JLabel();
        ams_lbl_prix_reduit = new javax.swing.JLabel();
        ams_tf_prix_reduit = new javax.swing.JTextField();
        ams_lbl_stock = new javax.swing.JLabel();
        ams_tf_stock = new javax.swing.JTextField();
        ams_btn_ajouter_produit = new javax.swing.JButton();
        ams_btn_modifier_produit = new javax.swing.JButton();
        ams_btn_supprimer_produit = new javax.swing.JButton();
        ams_rdobtn_oui = new javax.swing.JRadioButton();
        ams_rdobtn_non = new javax.swing.JRadioButton();
        categories = new javax.swing.JPanel();
        panel_c_ajout = new javax.swing.JPanel();
        a_c_lbl_nom_cat = new javax.swing.JLabel();
        a_c_tf_nom_cat = new javax.swing.JTextField();
        a_c_btn_ajouter_cat = new javax.swing.JButton();
        panel_c_modif_suppr = new javax.swing.JPanel();
        ms_c_lbl_categorie = new javax.swing.JLabel();
        ms_c_cbb_categorie = new javax.swing.JComboBox<>();
        ms_c_tf_nom_cat = new javax.swing.JTextField();
        ms_c_lbl_nom_cat = new javax.swing.JLabel();
        ms_c_btn_modifier_cat = new javax.swing.JButton();
        ms_c_btn_supprimer_cat = new javax.swing.JButton();
        panel_sc_ajout = new javax.swing.JPanel();
        a_sc_lbl_cat = new javax.swing.JLabel();
        a_sc_cbb_cat = new javax.swing.JComboBox<>();
        a_sc_lbl_nom_sous_cat = new javax.swing.JLabel();
        a_sc_tf_nom_sous_cat = new javax.swing.JTextField();
        a_sc_btn_ajouter_sous_cat = new javax.swing.JButton();
        panel_sc_modif_suppr = new javax.swing.JPanel();
        ms_sc_lbl_cat = new javax.swing.JLabel();
        ms_sc_cbb_cat = new javax.swing.JComboBox<>();
        ms_sc_lbl_sous_cat = new javax.swing.JLabel();
        ms_sc_cbb_sous_cat = new javax.swing.JComboBox<>();
        ms_sc_lbl_nom_sous_cat1 = new javax.swing.JLabel();
        ms_sc_tf_nom_sous_cat1 = new javax.swing.JTextField();
        ms_sc_btn_modifier_sous_cat = new javax.swing.JButton();
        ms_sc_btn_supprimer_sous_cat = new javax.swing.JButton();
        promotions = new javax.swing.JPanel();
        clients = new javax.swing.JPanel();
        BarreMenu = new javax.swing.JMenuBar();
        fichier = new javax.swing.JMenu();
        gestionCaracteristiques = new javax.swing.JMenuItem();
        gestionPromotions = new javax.swing.JMenuItem();
        gestionClients = new javax.swing.JMenuItem();
        charger = new javax.swing.JMenuItem();
        separatorGestionSave = new javax.swing.JPopupMenu.Separator();
        sauvegarder = new javax.swing.JMenuItem();
        separatorSaveQuit = new javax.swing.JPopupMenu.Separator();
        quitter = new javax.swing.JMenuItem();
        aPropos = new javax.swing.JMenu();
        version = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion stock");

        panel_recherche.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Rechercher un produit"));

        r_lbl_nom_produit.setText("Nom produit");
        r_lbl_nom_produit.setToolTipText("");

        r_lbl_categorie.setText("Catégories");

        r_cbb_categorie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item1", "Item2", "Item3", "Item4" }));
        r_cbb_categorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_cbb_categorieActionPerformed(evt);
            }
        });

        r_lbl_sous_cat.setText("Sous-catégorie");

        r_cbb_sous_cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        r_btn_rechercher.setText("Rechercher");

        r_btn_effacer.setText("Effacer");
        r_btn_effacer.setMaximumSize(new java.awt.Dimension(89, 22));
        r_btn_effacer.setMinimumSize(new java.awt.Dimension(89, 22));
        r_btn_effacer.setPreferredSize(new java.awt.Dimension(89, 22));

        javax.swing.GroupLayout panel_rechercheLayout = new javax.swing.GroupLayout(panel_recherche);
        panel_recherche.setLayout(panel_rechercheLayout);
        panel_rechercheLayout.setHorizontalGroup(
            panel_rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_rechercheLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_rechercheLayout.createSequentialGroup()
                        .addComponent(r_lbl_nom_produit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_rechercheLayout.createSequentialGroup()
                                .addGap(0, 566, Short.MAX_VALUE)
                                .addComponent(r_btn_rechercher)
                                .addGap(18, 18, 18)
                                .addComponent(r_btn_effacer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(r_tf_nom_produit)))
                    .addGroup(panel_rechercheLayout.createSequentialGroup()
                        .addComponent(r_lbl_categorie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r_cbb_categorie, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                        .addComponent(r_lbl_sous_cat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r_cbb_sous_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel_rechercheLayout.setVerticalGroup(
            panel_rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_rechercheLayout.createSequentialGroup()
                .addGroup(panel_rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r_lbl_nom_produit)
                    .addComponent(r_tf_nom_produit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(panel_rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r_lbl_categorie)
                    .addComponent(r_cbb_categorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r_cbb_sous_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r_lbl_sous_cat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r_btn_rechercher)
                    .addComponent(r_btn_effacer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panel_p_ajout_modif_suppr.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Ajouter - Modifier - Supprimer un produit"));

        ams_lbl_id_produit.setText("Id");

        ams_tf_id_produit.setMaximumSize(new java.awt.Dimension(30, 22));
        ams_tf_id_produit.setMinimumSize(new java.awt.Dimension(30, 22));
        ams_tf_id_produit.setPreferredSize(new java.awt.Dimension(30, 22));

        ams_p_lbl_categorie.setText("Catégories");

        ams_cbb_categorie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ams_cbb_categorie.setMinimumSize(new java.awt.Dimension(52, 22));
        ams_cbb_categorie.setPreferredSize(new java.awt.Dimension(60, 22));

        ams_p_lbl_sous_cat.setText("Sous-catégorie");

        ams_cbb_sous_cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ams_cbb_sous_cat.setMaximumSize(new java.awt.Dimension(60, 22));
        ams_cbb_sous_cat.setMinimumSize(new java.awt.Dimension(52, 22));
        ams_cbb_sous_cat.setPreferredSize(new java.awt.Dimension(60, 22));

        ams_lbl_nom_produit.setText("Nom produit");

        ams_lbl_description.setText("Description");

        ams_ta_description.setColumns(20);
        ams_ta_description.setRows(5);
        ams_scroll_description.setViewportView(ams_ta_description);

        ams_lbl_prix.setText("Prix");

        ams_tf_prix.setPreferredSize(new java.awt.Dimension(80, 22));

        ams_lbl_en_promotion.setText("En promotion");

        ams_lbl_prix_reduit.setText("Prix réduit");

        ams_tf_prix_reduit.setPreferredSize(new java.awt.Dimension(80, 22));
        ams_tf_prix_reduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ams_tf_prix_reduitActionPerformed(evt);
            }
        });

        ams_lbl_stock.setText("Quantité en stock");

        ams_tf_stock.setPreferredSize(new java.awt.Dimension(80, 22));

        ams_btn_ajouter_produit.setText("Ajouter");

        ams_btn_modifier_produit.setText("Modifier");

        ams_btn_supprimer_produit.setText("Supprimer");

        ams_btngrp_en_promotion.add(ams_rdobtn_oui);
        ams_rdobtn_oui.setText("Oui");

        ams_btngrp_en_promotion.add(ams_rdobtn_non);
        ams_rdobtn_non.setSelected(true);
        ams_rdobtn_non.setText("Non");

        javax.swing.GroupLayout panel_p_ajout_modif_supprLayout = new javax.swing.GroupLayout(panel_p_ajout_modif_suppr);
        panel_p_ajout_modif_suppr.setLayout(panel_p_ajout_modif_supprLayout);
        panel_p_ajout_modif_supprLayout.setHorizontalGroup(
            panel_p_ajout_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_p_ajout_modif_supprLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_p_ajout_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_p_ajout_modif_supprLayout.createSequentialGroup()
                        .addComponent(ams_lbl_id_produit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ams_tf_id_produit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ams_p_lbl_categorie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ams_cbb_categorie, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ams_p_lbl_sous_cat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ams_cbb_sous_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_p_ajout_modif_supprLayout.createSequentialGroup()
                        .addComponent(ams_btn_ajouter_produit)
                        .addGap(18, 18, 18)
                        .addComponent(ams_btn_modifier_produit)
                        .addGap(18, 18, 18)
                        .addComponent(ams_btn_supprimer_produit))
                    .addGroup(panel_p_ajout_modif_supprLayout.createSequentialGroup()
                        .addGroup(panel_p_ajout_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ams_lbl_nom_produit)
                            .addComponent(ams_lbl_description)
                            .addComponent(ams_lbl_prix, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_p_ajout_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ams_scroll_description)
                            .addComponent(ams_tf_nom_produiit)
                            .addGroup(panel_p_ajout_modif_supprLayout.createSequentialGroup()
                                .addComponent(ams_tf_prix, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ams_lbl_en_promotion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ams_rdobtn_oui)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ams_rdobtn_non)
                                .addGap(18, 18, 18)
                                .addComponent(ams_lbl_prix_reduit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ams_tf_prix_reduit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ams_lbl_stock)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ams_tf_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        panel_p_ajout_modif_supprLayout.setVerticalGroup(
            panel_p_ajout_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_p_ajout_modif_supprLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_p_ajout_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ams_lbl_id_produit)
                    .addComponent(ams_tf_id_produit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ams_p_lbl_categorie)
                    .addComponent(ams_cbb_categorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ams_cbb_sous_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ams_p_lbl_sous_cat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_p_ajout_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ams_lbl_nom_produit)
                    .addComponent(ams_tf_nom_produiit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel_p_ajout_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_p_ajout_modif_supprLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(ams_lbl_description))
                    .addGroup(panel_p_ajout_modif_supprLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ams_scroll_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_p_ajout_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ams_tf_prix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ams_lbl_prix)
                    .addComponent(ams_lbl_prix_reduit)
                    .addComponent(ams_tf_prix_reduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ams_lbl_stock)
                    .addComponent(ams_lbl_en_promotion)
                    .addComponent(ams_rdobtn_oui)
                    .addComponent(ams_rdobtn_non)
                    .addComponent(ams_tf_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(panel_p_ajout_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ams_btn_supprimer_produit)
                    .addComponent(ams_btn_modifier_produit)
                    .addComponent(ams_btn_ajouter_produit))
                .addContainerGap())
        );

        javax.swing.GroupLayout produitsLayout = new javax.swing.GroupLayout(produits);
        produits.setLayout(produitsLayout);
        produitsLayout.setHorizontalGroup(
            produitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produitsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(produitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(produitsLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(panel_p_ajout_modif_suppr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panel_recherche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        produitsLayout.setVerticalGroup(
            produitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produitsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_p_ajout_modif_suppr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_recherche.getAccessibleContext().setAccessibleName("Recherche de produit");

        tpanel_onglets.addTab("Produits", produits);

        panel_c_ajout.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Ajouter une catégorie"));

        a_c_lbl_nom_cat.setText("Nom catégorie");

        a_c_btn_ajouter_cat.setText("Ajouter");

        javax.swing.GroupLayout panel_c_ajoutLayout = new javax.swing.GroupLayout(panel_c_ajout);
        panel_c_ajout.setLayout(panel_c_ajoutLayout);
        panel_c_ajoutLayout.setHorizontalGroup(
            panel_c_ajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_c_ajoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(a_c_lbl_nom_cat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a_c_tf_nom_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(a_c_btn_ajouter_cat)
                .addContainerGap())
        );
        panel_c_ajoutLayout.setVerticalGroup(
            panel_c_ajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_c_ajoutLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_c_ajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a_c_lbl_nom_cat)
                    .addComponent(a_c_tf_nom_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a_c_btn_ajouter_cat))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panel_c_modif_suppr.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Modifier - Supprimer une catégorie"));
        panel_c_modif_suppr.setPreferredSize(new java.awt.Dimension(823, 66));

        ms_c_lbl_categorie.setText("Catégories");

        ms_c_cbb_categorie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ms_c_cbb_categorie.setMinimumSize(new java.awt.Dimension(52, 22));
        ms_c_cbb_categorie.setPreferredSize(new java.awt.Dimension(60, 22));

        ms_c_lbl_nom_cat.setText("Nom catégorie");

        ms_c_btn_modifier_cat.setText("Modifier");

        ms_c_btn_supprimer_cat.setText("Supprimer");
        ms_c_btn_supprimer_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_c_btn_supprimer_catActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_c_modif_supprLayout = new javax.swing.GroupLayout(panel_c_modif_suppr);
        panel_c_modif_suppr.setLayout(panel_c_modif_supprLayout);
        panel_c_modif_supprLayout.setHorizontalGroup(
            panel_c_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_c_modif_supprLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ms_c_lbl_categorie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ms_c_cbb_categorie, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ms_c_lbl_nom_cat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ms_c_tf_nom_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(ms_c_btn_modifier_cat)
                .addGap(18, 18, 18)
                .addComponent(ms_c_btn_supprimer_cat)
                .addContainerGap())
        );
        panel_c_modif_supprLayout.setVerticalGroup(
            panel_c_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_c_modif_supprLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_c_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_c_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ms_c_lbl_nom_cat)
                        .addComponent(ms_c_tf_nom_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ms_c_btn_modifier_cat)
                        .addComponent(ms_c_btn_supprimer_cat))
                    .addGroup(panel_c_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ms_c_lbl_categorie)
                        .addComponent(ms_c_cbb_categorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panel_sc_ajout.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Ajouter une sous-catégorie"));
        panel_sc_ajout.setPreferredSize(new java.awt.Dimension(468, 66));

        a_sc_lbl_cat.setText("Catégories");

        a_sc_cbb_cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        a_sc_cbb_cat.setMinimumSize(new java.awt.Dimension(52, 22));
        a_sc_cbb_cat.setPreferredSize(new java.awt.Dimension(60, 22));

        a_sc_lbl_nom_sous_cat.setText("Nom sous-catégorie");

        a_sc_btn_ajouter_sous_cat.setText("Ajouter");

        javax.swing.GroupLayout panel_sc_ajoutLayout = new javax.swing.GroupLayout(panel_sc_ajout);
        panel_sc_ajout.setLayout(panel_sc_ajoutLayout);
        panel_sc_ajoutLayout.setHorizontalGroup(
            panel_sc_ajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_sc_ajoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(a_sc_lbl_cat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a_sc_cbb_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(a_sc_lbl_nom_sous_cat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a_sc_tf_nom_sous_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(a_sc_btn_ajouter_sous_cat)
                .addContainerGap())
        );
        panel_sc_ajoutLayout.setVerticalGroup(
            panel_sc_ajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_sc_ajoutLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_sc_ajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_sc_ajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(a_sc_lbl_nom_sous_cat)
                        .addComponent(a_sc_tf_nom_sous_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a_sc_btn_ajouter_sous_cat))
                    .addGroup(panel_sc_ajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(a_sc_lbl_cat)
                        .addComponent(a_sc_cbb_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panel_sc_modif_suppr.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Modifier - Supprimer une sous-catégorie"));

        ms_sc_lbl_cat.setText("Catégories");

        ms_sc_cbb_cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ms_sc_cbb_cat.setMinimumSize(new java.awt.Dimension(52, 22));
        ms_sc_cbb_cat.setPreferredSize(new java.awt.Dimension(60, 22));

        ms_sc_lbl_sous_cat.setText("Sous-catégorie");

        ms_sc_cbb_sous_cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ms_sc_cbb_sous_cat.setMaximumSize(new java.awt.Dimension(60, 22));
        ms_sc_cbb_sous_cat.setMinimumSize(new java.awt.Dimension(52, 22));
        ms_sc_cbb_sous_cat.setPreferredSize(new java.awt.Dimension(60, 22));

        ms_sc_lbl_nom_sous_cat1.setText("Nom sous-catégorie");

        ms_sc_btn_modifier_sous_cat.setText("Modifier");

        ms_sc_btn_supprimer_sous_cat.setText("Supprimer");

        javax.swing.GroupLayout panel_sc_modif_supprLayout = new javax.swing.GroupLayout(panel_sc_modif_suppr);
        panel_sc_modif_suppr.setLayout(panel_sc_modif_supprLayout);
        panel_sc_modif_supprLayout.setHorizontalGroup(
            panel_sc_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_sc_modif_supprLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_sc_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_sc_modif_supprLayout.createSequentialGroup()
                        .addComponent(ms_sc_lbl_nom_sous_cat1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ms_sc_tf_nom_sous_cat1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ms_sc_btn_modifier_sous_cat)
                        .addGap(18, 18, 18)
                        .addComponent(ms_sc_btn_supprimer_sous_cat))
                    .addGroup(panel_sc_modif_supprLayout.createSequentialGroup()
                        .addComponent(ms_sc_lbl_cat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ms_sc_cbb_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ms_sc_lbl_sous_cat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ms_sc_cbb_sous_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_sc_modif_supprLayout.setVerticalGroup(
            panel_sc_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_sc_modif_supprLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_sc_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ms_sc_lbl_cat)
                    .addComponent(ms_sc_cbb_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ms_sc_cbb_sous_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ms_sc_lbl_sous_cat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_sc_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_sc_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ms_sc_btn_supprimer_sous_cat)
                        .addComponent(ms_sc_btn_modifier_sous_cat))
                    .addGroup(panel_sc_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ms_sc_lbl_nom_sous_cat1)
                        .addComponent(ms_sc_tf_nom_sous_cat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout categoriesLayout = new javax.swing.GroupLayout(categories);
        categories.setLayout(categoriesLayout);
        categoriesLayout.setHorizontalGroup(
            categoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_c_ajout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_c_modif_suppr, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
            .addComponent(panel_sc_ajout, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
            .addComponent(panel_sc_modif_suppr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        categoriesLayout.setVerticalGroup(
            categoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoriesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_c_ajout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_c_modif_suppr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_sc_ajout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_sc_modif_suppr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        tpanel_onglets.addTab("Catégories", categories);

        javax.swing.GroupLayout promotionsLayout = new javax.swing.GroupLayout(promotions);
        promotions.setLayout(promotionsLayout);
        promotionsLayout.setHorizontalGroup(
            promotionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 873, Short.MAX_VALUE)
        );
        promotionsLayout.setVerticalGroup(
            promotionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        tpanel_onglets.addTab("Promotions", promotions);

        javax.swing.GroupLayout clientsLayout = new javax.swing.GroupLayout(clients);
        clients.setLayout(clientsLayout);
        clientsLayout.setHorizontalGroup(
            clientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 873, Short.MAX_VALUE)
        );
        clientsLayout.setVerticalGroup(
            clientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        tpanel_onglets.addTab("Clients", clients);

        javax.swing.GroupLayout panel_generalLayout = new javax.swing.GroupLayout(panel_general);
        panel_general.setLayout(panel_generalLayout);
        panel_generalLayout.setHorizontalGroup(
            panel_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_generalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpanel_onglets)
                .addContainerGap())
        );
        panel_generalLayout.setVerticalGroup(
            panel_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_generalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpanel_onglets, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panel_general, java.awt.BorderLayout.CENTER);

        BarreMenu.setToolTipText("Test");

        fichier.setText("Fichier");

        gestionCaracteristiques.setText("Gestion Caractéristiques");
        fichier.add(gestionCaracteristiques);

        gestionPromotions.setText("Gestion Promotions");
        fichier.add(gestionPromotions);

        gestionClients.setText("Gestion Clients");
        fichier.add(gestionClients);

        charger.setText("Charger");
        fichier.add(charger);
        fichier.add(separatorGestionSave);

        sauvegarder.setText("Sauvegarder");
        fichier.add(sauvegarder);
        fichier.add(separatorSaveQuit);

        quitter.setText("Quitter");
        fichier.add(quitter);

        BarreMenu.add(fichier);

        aPropos.setText("A propos");

        version.setText("Version");
        aPropos.add(version);

        BarreMenu.add(aPropos);

        setJMenuBar(BarreMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ams_tf_prix_reduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ams_tf_prix_reduitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ams_tf_prix_reduitActionPerformed

    private void ms_c_btn_supprimer_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_c_btn_supprimer_catActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ms_c_btn_supprimer_catActionPerformed

    private void r_cbb_categorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_cbb_categorieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r_cbb_categorieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new InterfaceGraphique().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarreMenu;
    private javax.swing.JMenu aPropos;
    private javax.swing.JButton a_c_btn_ajouter_cat;
    private javax.swing.JLabel a_c_lbl_nom_cat;
    private javax.swing.JTextField a_c_tf_nom_cat;
    private javax.swing.JButton a_sc_btn_ajouter_sous_cat;
    private javax.swing.JComboBox<String> a_sc_cbb_cat;
    private javax.swing.JLabel a_sc_lbl_cat;
    private javax.swing.JLabel a_sc_lbl_nom_sous_cat;
    private javax.swing.JTextField a_sc_tf_nom_sous_cat;
    private javax.swing.JButton ams_btn_ajouter_produit;
    private javax.swing.JButton ams_btn_modifier_produit;
    private javax.swing.JButton ams_btn_supprimer_produit;
    private javax.swing.ButtonGroup ams_btngrp_en_promotion;
    private javax.swing.JComboBox<String> ams_cbb_categorie;
    private javax.swing.JComboBox<String> ams_cbb_sous_cat;
    private javax.swing.JLabel ams_lbl_description;
    private javax.swing.JLabel ams_lbl_en_promotion;
    private javax.swing.JLabel ams_lbl_id_produit;
    private javax.swing.JLabel ams_lbl_nom_produit;
    private javax.swing.JLabel ams_lbl_prix;
    private javax.swing.JLabel ams_lbl_prix_reduit;
    private javax.swing.JLabel ams_lbl_stock;
    private javax.swing.JLabel ams_p_lbl_categorie;
    private javax.swing.JLabel ams_p_lbl_sous_cat;
    private javax.swing.JRadioButton ams_rdobtn_non;
    private javax.swing.JRadioButton ams_rdobtn_oui;
    private javax.swing.JScrollPane ams_scroll_description;
    private javax.swing.JTextArea ams_ta_description;
    private javax.swing.JTextField ams_tf_id_produit;
    private javax.swing.JTextField ams_tf_nom_produiit;
    private javax.swing.JTextField ams_tf_prix;
    private javax.swing.JTextField ams_tf_prix_reduit;
    private javax.swing.JTextField ams_tf_stock;
    private javax.swing.JPanel categories;
    private javax.swing.JMenuItem charger;
    private javax.swing.JPanel clients;
    private javax.swing.JMenu fichier;
    private javax.swing.JMenuItem gestionCaracteristiques;
    private javax.swing.JMenuItem gestionClients;
    private javax.swing.JMenuItem gestionPromotions;
    private javax.swing.JButton ms_c_btn_modifier_cat;
    private javax.swing.JButton ms_c_btn_supprimer_cat;
    private javax.swing.JComboBox<String> ms_c_cbb_categorie;
    private javax.swing.JLabel ms_c_lbl_categorie;
    private javax.swing.JLabel ms_c_lbl_nom_cat;
    private javax.swing.JTextField ms_c_tf_nom_cat;
    private javax.swing.JButton ms_sc_btn_modifier_sous_cat;
    private javax.swing.JButton ms_sc_btn_supprimer_sous_cat;
    private javax.swing.JComboBox<String> ms_sc_cbb_cat;
    private javax.swing.JComboBox<String> ms_sc_cbb_sous_cat;
    private javax.swing.JLabel ms_sc_lbl_cat;
    private javax.swing.JLabel ms_sc_lbl_nom_sous_cat1;
    private javax.swing.JLabel ms_sc_lbl_sous_cat;
    private javax.swing.JTextField ms_sc_tf_nom_sous_cat1;
    private javax.swing.JPanel panel_c_ajout;
    private javax.swing.JPanel panel_c_modif_suppr;
    private javax.swing.JPanel panel_general;
    private javax.swing.JPanel panel_p_ajout_modif_suppr;
    private javax.swing.JPanel panel_recherche;
    private javax.swing.JPanel panel_sc_ajout;
    private javax.swing.JPanel panel_sc_modif_suppr;
    private javax.swing.JPanel produits;
    private javax.swing.JPanel promotions;
    private javax.swing.JMenuItem quitter;
    private javax.swing.JButton r_btn_effacer;
    private javax.swing.JButton r_btn_rechercher;
    private javax.swing.JComboBox<String> r_cbb_sous_cat;
    private javax.swing.JLabel r_lbl_categorie;
    private javax.swing.JLabel r_lbl_nom_produit;
    private javax.swing.JLabel r_lbl_sous_cat;
    private javax.swing.JTextField r_tf_nom_produit;
    private javax.swing.JMenuItem sauvegarder;
    private javax.swing.JPopupMenu.Separator separatorGestionSave;
    private javax.swing.JPopupMenu.Separator separatorSaveQuit;
    private javax.swing.JTabbedPane tpanel_onglets;
    private javax.swing.JMenuItem version;
    // End of variables declaration//GEN-END:variables
}
