package gestioncatalogue.vue;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
//import javax.swing.ComboBoxModel;
//import javax.swing.DefaultComboBoxModel;
//import javax.swing.JOptionPane;


import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.event.ItemEvent;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import static gestioncatalogue.dao.CategoriesDAO.*;

import gestioncatalogue.dao.Produit;

public class InterfaceGraphique extends javax.swing.JFrame {
        
    //private Object[] tabCategories;
    //private Object[] tabSousCatChaise;
    //private Object[] tabSousCatLit;
    //private Object[] tabSousCatRangement;
    //private Object[] tabSousCatTable;
    //private final ComboBoxModel<String> modeleDesCategories;
    //private ComboBoxModel<String> modeleDesSousCategories;
    
    private static List<Produit> Produits;
    private static final List<String> listeCat = getCategories();
        
    public InterfaceGraphique() {
        
        Produits = new ArrayList<>();
        Produits.add(new Produit ("Tabloid", "Sympa la table", 100, 10));
        Produits.add(new Produit ("Litoid", "Sympa le lit", 200, 20));
        Produits.add(new Produit ("Rangeoid", "Sympa le rangement", 300, 30));
        
        Collections.sort(Produits);
        
        //tabCategories = Categories.getCategories().toArray();
        //tabSousCatChaise = SousCatChaise.getSousCatChaise().toArray();
        //tabSousCatLit = SousCatLit.getSousCatLit().toArray();
        //tabSousCatRangement = SousCatRange.getSousCatRange().toArray();
        //tabSousCatTable = SousCatTable.getSousCatTable().toArray();
        
        //modeleDesCategories = new DefaultComboBoxModel(tabCategories);
        //modeleDesSousCategories = new DefaultComboBoxModel(); 
        
         initComponents();

         fillCbbCat(r_cbb_categorie);
         fillCbbCat(ams_cbb_categorie);
         fillCbbCat(ms_c_cbb_categorie);
         fillCbbCat(a_sc_cbb_cat);
         fillCbbCat(ms_sc_cbb_cat);         
    }
    
    public static void fillCbbCat(JComboBox<String> cbb) {
            for (String cat : listeCat) {
                cbb.addItem(cat);
            }    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ams_btngrp_en_promotion = new javax.swing.ButtonGroup();
        panel_general = new javax.swing.JPanel();
        tpanel_onglets = new javax.swing.JTabbedPane();
        onglet_produits = new javax.swing.JPanel();
        panel_recherche = new javax.swing.JPanel();
        r_lbl_nom_produit = new javax.swing.JLabel();
        r_tf_nom_produit = new javax.swing.JTextField();
        r_lbl_categorie = new javax.swing.JLabel();
        r_cbb_categorie = new javax.swing.JComboBox<>();
        r_lbl_sous_cat = new javax.swing.JLabel();
        r_cbb_sous_cat = new javax.swing.JComboBox<>();
        r_btn_rechercher = new javax.swing.JButton();
        r_btn_effacer = new javax.swing.JButton();
        panel_p_ajout_modif_suppr = new javax.swing.JPanel();
        ams_lbl_id_produit = new javax.swing.JLabel();
        ams_tf_id_produit = new javax.swing.JTextField();
        ams_p_lbl_categorie = new javax.swing.JLabel();
        ams_cbb_categorie = new javax.swing.JComboBox<>();
        ams_p_lbl_sous_cat = new javax.swing.JLabel();
        ams_cbb_sous_cat = new javax.swing.JComboBox<>();
        ams_lbl_nom_produit = new javax.swing.JLabel();
        ams_tf_nom_produit = new javax.swing.JTextField();
        ams_lbl_description = new javax.swing.JLabel();
        ams_scroll_description = new javax.swing.JScrollPane();
        ams_ta_description = new javax.swing.JTextArea();
        ams_lbl_prix = new javax.swing.JLabel();
        ams_tf_prix = new javax.swing.JTextField();
        ams_lbl_en_promotion = new javax.swing.JLabel();
        ams_lbl_prix_reduit = new javax.swing.JLabel();
        ams_lbl_taux_promo = new javax.swing.JLabel();
        ams_tf_taux_promo = new javax.swing.JTextField();
        ams_tf_prix_reduit = new javax.swing.JTextField();
        ams_lbl_stock = new javax.swing.JLabel();
        ams_tf_stock = new javax.swing.JTextField();
        ams_btn_ajouter_produit = new javax.swing.JButton();
        ams_btn_modifier_produit = new javax.swing.JButton();
        ams_btn_supprimer_produit = new javax.swing.JButton();
        ams_rdobtn_oui = new javax.swing.JRadioButton();
        ams_rdobtn_non = new javax.swing.JRadioButton();
        ams_btn_effacer = new javax.swing.JButton();
        onglet_categories = new javax.swing.JPanel();
        panel_c_ajout = new javax.swing.JPanel();
        a_c_lbl_nom_cat = new javax.swing.JLabel();
        a_c_tf_nom_cat = new javax.swing.JTextField();
        a_c_btn_ajouter_cat = new javax.swing.JButton();
        panel_c_modif_suppr = new javax.swing.JPanel();
        ms_c_lbl_categorie = new javax.swing.JLabel();
        ms_c_cbb_categorie = new javax.swing.JComboBox<>();
        ms_c_tf_nom_cat = new javax.swing.JTextField();
        ms_c_lbl_nom_cat = new javax.swing.JLabel();
        ms_c_btn_modifier_cat = new javax.swing.JButton();
        ms_c_btn_supprimer_cat = new javax.swing.JButton();
        panel_sc_ajout = new javax.swing.JPanel();
        a_sc_lbl_cat = new javax.swing.JLabel();
        a_sc_cbb_cat = new javax.swing.JComboBox<>();
        a_sc_lbl_nom_sous_cat = new javax.swing.JLabel();
        a_sc_tf_nom_sous_cat = new javax.swing.JTextField();
        a_sc_btn_ajouter_sous_cat = new javax.swing.JButton();
        panel_sc_modif_suppr = new javax.swing.JPanel();
        ms_sc_lbl_cat = new javax.swing.JLabel();
        ms_sc_cbb_cat = new javax.swing.JComboBox<>();
        ms_sc_lbl_sous_cat = new javax.swing.JLabel();
        ms_sc_cbb_sous_cat = new javax.swing.JComboBox<>();
        ms_sc_lbl_nom_sous_cat1 = new javax.swing.JLabel();
        ms_sc_tf_nom_sous_cat1 = new javax.swing.JTextField();
        ms_sc_btn_modifier_sous_cat = new javax.swing.JButton();
        ms_sc_btn_supprimer_sous_cat = new javax.swing.JButton();
        onglet_promotions = new javax.swing.JPanel();
        onglet_clients = new javax.swing.JPanel();
        BarreMenu = new javax.swing.JMenuBar();
        fichier = new javax.swing.JMenu();
        gestionProduits = new javax.swing.JMenuItem();
        gestionCategories = new javax.swing.JMenuItem();
        gestionPromotions = new javax.swing.JMenuItem();
        gestionClients = new javax.swing.JMenuItem();
        charger = new javax.swing.JMenuItem();
        separatorGestionSave = new javax.swing.JPopupMenu.Separator();
        sauvegarder = new javax.swing.JMenuItem();
        separatorSaveQuit = new javax.swing.JPopupMenu.Separator();
        quitter = new javax.swing.JMenuItem();
        aPropos = new javax.swing.JMenu();
        version = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gestion stock");

        panel_recherche.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Rechercher un produit"));

        r_lbl_nom_produit.setText("Nom produit");
        r_lbl_nom_produit.setToolTipText("");

        r_lbl_categorie.setText("Catégories");

        r_cbb_categorie.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                r_cbb_categorieItemStateChanged(evt);
            }
        });

        r_lbl_sous_cat.setText("Sous-catégorie");

        r_btn_rechercher.setText("Rechercher");

        r_btn_effacer.setText("Effacer");
        r_btn_effacer.setMaximumSize(new java.awt.Dimension(89, 22));
        r_btn_effacer.setMinimumSize(new java.awt.Dimension(89, 22));
        r_btn_effacer.setPreferredSize(new java.awt.Dimension(89, 22));
        r_btn_effacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_btn_effacerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_rechercheLayout = new javax.swing.GroupLayout(panel_recherche);
        panel_recherche.setLayout(panel_rechercheLayout);
        panel_rechercheLayout.setHorizontalGroup(
            panel_rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_rechercheLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_rechercheLayout.createSequentialGroup()
                        .addComponent(r_lbl_nom_produit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_rechercheLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(r_btn_rechercher)
                                .addGap(18, 18, 18)
                                .addComponent(r_btn_effacer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(r_tf_nom_produit)))
                    .addGroup(panel_rechercheLayout.createSequentialGroup()
                        .addComponent(r_lbl_categorie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r_cbb_categorie, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(r_lbl_sous_cat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(r_cbb_sous_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel_rechercheLayout.setVerticalGroup(
            panel_rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_rechercheLayout.createSequentialGroup()
                .addGroup(panel_rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r_lbl_nom_produit)
                    .addComponent(r_tf_nom_produit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(panel_rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r_lbl_categorie)
                    .addComponent(r_cbb_categorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r_cbb_sous_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r_lbl_sous_cat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r_btn_rechercher)
                    .addComponent(r_btn_effacer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panel_p_ajout_modif_suppr.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Ajouter - Modifier - Supprimer un produit"));

        ams_lbl_id_produit.setText("Id");

        ams_tf_id_produit.setEditable(false);
        ams_tf_id_produit.setBackground(new java.awt.Color(205, 205, 205));
        ams_tf_id_produit.setMaximumSize(new java.awt.Dimension(30, 22));
        ams_tf_id_produit.setMinimumSize(new java.awt.Dimension(30, 22));
        ams_tf_id_produit.setPreferredSize(new java.awt.Dimension(30, 22));

        ams_p_lbl_categorie.setText("Catégories");

        ams_cbb_categorie.setMinimumSize(new java.awt.Dimension(52, 22));
        ams_cbb_categorie.setPreferredSize(new java.awt.Dimension(60, 22));
        ams_cbb_categorie.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ams_cbb_categorieItemStateChanged(evt);
            }
        });

        ams_p_lbl_sous_cat.setText("Sous-catégorie");

        ams_cbb_sous_cat.setMaximumSize(new java.awt.Dimension(60, 22));
        ams_cbb_sous_cat.setMinimumSize(new java.awt.Dimension(52, 22));
        ams_cbb_sous_cat.setPreferredSize(new java.awt.Dimension(60, 22));

        ams_lbl_nom_produit.setText("Nom produit");

        ams_lbl_description.setText("Description");

        ams_ta_description.setColumns(20);
        ams_ta_description.setRows(5);
        ams_scroll_description.setViewportView(ams_ta_description);

        ams_lbl_prix.setText("Prix");

        ams_tf_prix.setPreferredSize(new java.awt.Dimension(80, 22));

        ams_lbl_en_promotion.setText("En promotion");

        ams_lbl_prix_reduit.setText("Prix réduit");

        ams_lbl_taux_promo.setText("Taux promo");

        ams_tf_taux_promo.setPreferredSize(new java.awt.Dimension(80, 22));

        ams_tf_prix_reduit.setPreferredSize(new java.awt.Dimension(80, 22));

        ams_lbl_stock.setText("Quantité en stock");

        ams_tf_stock.setPreferredSize(new java.awt.Dimension(80, 22));

        ams_btn_ajouter_produit.setText("Ajouter");

        ams_btn_modifier_produit.setText("Modifier");

        ams_btn_supprimer_produit.setText("Supprimer");

        ams_btngrp_en_promotion.add(ams_rdobtn_oui);
        ams_rdobtn_oui.setText("Oui");

        ams_btngrp_en_promotion.add(ams_rdobtn_non);
        ams_rdobtn_non.setSelected(true);
        ams_rdobtn_non.setText("Non");

        ams_btn_effacer.setText("Effacer");
        ams_btn_effacer.setMaximumSize(new java.awt.Dimension(89, 22));
        ams_btn_effacer.setMinimumSize(new java.awt.Dimension(89, 22));
        ams_btn_effacer.setPreferredSize(new java.awt.Dimension(89, 22));
        ams_btn_effacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ams_btn_effacerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_p_ajout_modif_supprLayout = new javax.swing.GroupLayout(panel_p_ajout_modif_suppr);
        panel_p_ajout_modif_suppr.setLayout(panel_p_ajout_modif_supprLayout);
        panel_p_ajout_modif_supprLayout.setHorizontalGroup(
            panel_p_ajout_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_p_ajout_modif_supprLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_p_ajout_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_p_ajout_modif_supprLayout.createSequentialGroup()
                        .addComponent(ams_lbl_id_produit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ams_tf_id_produit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ams_p_lbl_categorie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ams_cbb_categorie, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ams_p_lbl_sous_cat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ams_cbb_sous_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_p_ajout_modif_supprLayout.createSequentialGroup()
                        .addGroup(panel_p_ajout_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ams_lbl_nom_produit)
                            .addComponent(ams_lbl_description)
                            .addComponent(ams_lbl_prix, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_p_ajout_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ams_scroll_description)
                            .addComponent(ams_tf_nom_produit)
                            .addGroup(panel_p_ajout_modif_supprLayout.createSequentialGroup()
                                .addComponent(ams_tf_prix, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ams_lbl_en_promotion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ams_rdobtn_oui)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ams_rdobtn_non)
                                .addGap(18, 18, 18)
                                .addComponent(ams_lbl_taux_promo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ams_tf_taux_promo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ams_lbl_prix_reduit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ams_tf_prix_reduit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ams_lbl_stock)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ams_tf_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_p_ajout_modif_supprLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ams_btn_ajouter_produit)
                        .addGap(18, 18, 18)
                        .addComponent(ams_btn_modifier_produit)
                        .addGap(18, 18, 18)
                        .addComponent(ams_btn_supprimer_produit)
                        .addGap(18, 18, 18)
                        .addComponent(ams_btn_effacer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel_p_ajout_modif_supprLayout.setVerticalGroup(
            panel_p_ajout_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_p_ajout_modif_supprLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_p_ajout_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ams_lbl_id_produit)
                    .addComponent(ams_tf_id_produit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ams_p_lbl_categorie)
                    .addComponent(ams_cbb_categorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ams_cbb_sous_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ams_p_lbl_sous_cat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_p_ajout_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ams_lbl_nom_produit)
                    .addComponent(ams_tf_nom_produit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel_p_ajout_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_p_ajout_modif_supprLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(ams_lbl_description))
                    .addGroup(panel_p_ajout_modif_supprLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ams_scroll_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_p_ajout_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_p_ajout_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ams_tf_prix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ams_lbl_prix)
                        .addComponent(ams_lbl_en_promotion)
                        .addComponent(ams_rdobtn_oui)
                        .addComponent(ams_rdobtn_non))
                    .addGroup(panel_p_ajout_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ams_lbl_taux_promo)
                        .addComponent(ams_tf_taux_promo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_p_ajout_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ams_lbl_prix_reduit)
                        .addComponent(ams_tf_prix_reduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_p_ajout_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ams_lbl_stock)
                        .addComponent(ams_tf_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(panel_p_ajout_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ams_btn_supprimer_produit)
                    .addComponent(ams_btn_modifier_produit)
                    .addComponent(ams_btn_ajouter_produit)
                    .addComponent(ams_btn_effacer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout onglet_produitsLayout = new javax.swing.GroupLayout(onglet_produits);
        onglet_produits.setLayout(onglet_produitsLayout);
        onglet_produitsLayout.setHorizontalGroup(
            onglet_produitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(onglet_produitsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(onglet_produitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(onglet_produitsLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(panel_p_ajout_modif_suppr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panel_recherche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        onglet_produitsLayout.setVerticalGroup(
            onglet_produitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(onglet_produitsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_p_ajout_modif_suppr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_recherche.getAccessibleContext().setAccessibleName("Recherche de produit");

        tpanel_onglets.addTab("Produits", onglet_produits);

        panel_c_ajout.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Ajouter une catégorie"));

        a_c_lbl_nom_cat.setText("Nom catégorie");

        a_c_btn_ajouter_cat.setText("Ajouter");

        javax.swing.GroupLayout panel_c_ajoutLayout = new javax.swing.GroupLayout(panel_c_ajout);
        panel_c_ajout.setLayout(panel_c_ajoutLayout);
        panel_c_ajoutLayout.setHorizontalGroup(
            panel_c_ajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_c_ajoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(a_c_lbl_nom_cat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a_c_tf_nom_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(a_c_btn_ajouter_cat)
                .addContainerGap())
        );
        panel_c_ajoutLayout.setVerticalGroup(
            panel_c_ajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_c_ajoutLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_c_ajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a_c_lbl_nom_cat)
                    .addComponent(a_c_tf_nom_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(a_c_btn_ajouter_cat))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panel_c_modif_suppr.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Modifier - Supprimer une catégorie"));
        panel_c_modif_suppr.setPreferredSize(new java.awt.Dimension(823, 66));

        ms_c_lbl_categorie.setText("Catégories");

        ms_c_cbb_categorie.setMinimumSize(new java.awt.Dimension(52, 22));
        ms_c_cbb_categorie.setPreferredSize(new java.awt.Dimension(60, 22));

        ms_c_lbl_nom_cat.setText("Nom catégorie");

        ms_c_btn_modifier_cat.setText("Modifier");

        ms_c_btn_supprimer_cat.setText("Supprimer");
        ms_c_btn_supprimer_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_c_btn_supprimer_catActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_c_modif_supprLayout = new javax.swing.GroupLayout(panel_c_modif_suppr);
        panel_c_modif_suppr.setLayout(panel_c_modif_supprLayout);
        panel_c_modif_supprLayout.setHorizontalGroup(
            panel_c_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_c_modif_supprLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ms_c_lbl_categorie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ms_c_cbb_categorie, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ms_c_lbl_nom_cat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ms_c_tf_nom_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(ms_c_btn_modifier_cat)
                .addGap(18, 18, 18)
                .addComponent(ms_c_btn_supprimer_cat)
                .addContainerGap())
        );
        panel_c_modif_supprLayout.setVerticalGroup(
            panel_c_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_c_modif_supprLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_c_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_c_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ms_c_lbl_nom_cat)
                        .addComponent(ms_c_tf_nom_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ms_c_btn_modifier_cat)
                        .addComponent(ms_c_btn_supprimer_cat))
                    .addGroup(panel_c_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ms_c_lbl_categorie)
                        .addComponent(ms_c_cbb_categorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panel_sc_ajout.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Ajouter une sous-catégorie"));
        panel_sc_ajout.setPreferredSize(new java.awt.Dimension(468, 66));

        a_sc_lbl_cat.setText("Catégories");

        a_sc_cbb_cat.setMinimumSize(new java.awt.Dimension(52, 22));
        a_sc_cbb_cat.setPreferredSize(new java.awt.Dimension(60, 22));

        a_sc_lbl_nom_sous_cat.setText("Nom sous-catégorie");

        a_sc_btn_ajouter_sous_cat.setText("Ajouter");

        javax.swing.GroupLayout panel_sc_ajoutLayout = new javax.swing.GroupLayout(panel_sc_ajout);
        panel_sc_ajout.setLayout(panel_sc_ajoutLayout);
        panel_sc_ajoutLayout.setHorizontalGroup(
            panel_sc_ajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_sc_ajoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(a_sc_lbl_cat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a_sc_cbb_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(a_sc_lbl_nom_sous_cat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a_sc_tf_nom_sous_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(a_sc_btn_ajouter_sous_cat)
                .addContainerGap())
        );
        panel_sc_ajoutLayout.setVerticalGroup(
            panel_sc_ajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_sc_ajoutLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_sc_ajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_sc_ajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(a_sc_lbl_nom_sous_cat)
                        .addComponent(a_sc_tf_nom_sous_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(a_sc_btn_ajouter_sous_cat))
                    .addGroup(panel_sc_ajoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(a_sc_lbl_cat)
                        .addComponent(a_sc_cbb_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panel_sc_modif_suppr.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Modifier - Supprimer une sous-catégorie"));

        ms_sc_lbl_cat.setText("Catégories");

        ms_sc_cbb_cat.setMinimumSize(new java.awt.Dimension(52, 22));
        ms_sc_cbb_cat.setPreferredSize(new java.awt.Dimension(60, 22));
        ms_sc_cbb_cat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ms_sc_cbb_catItemStateChanged(evt);
            }
        });

        ms_sc_lbl_sous_cat.setText("Sous-catégorie");

        ms_sc_cbb_sous_cat.setMaximumSize(new java.awt.Dimension(60, 22));
        ms_sc_cbb_sous_cat.setMinimumSize(new java.awt.Dimension(52, 22));
        ms_sc_cbb_sous_cat.setPreferredSize(new java.awt.Dimension(60, 22));

        ms_sc_lbl_nom_sous_cat1.setText("Nom sous-catégorie");

        ms_sc_btn_modifier_sous_cat.setText("Modifier");

        ms_sc_btn_supprimer_sous_cat.setText("Supprimer");

        javax.swing.GroupLayout panel_sc_modif_supprLayout = new javax.swing.GroupLayout(panel_sc_modif_suppr);
        panel_sc_modif_suppr.setLayout(panel_sc_modif_supprLayout);
        panel_sc_modif_supprLayout.setHorizontalGroup(
            panel_sc_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_sc_modif_supprLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_sc_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_sc_modif_supprLayout.createSequentialGroup()
                        .addComponent(ms_sc_lbl_nom_sous_cat1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ms_sc_tf_nom_sous_cat1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ms_sc_btn_modifier_sous_cat)
                        .addGap(18, 18, 18)
                        .addComponent(ms_sc_btn_supprimer_sous_cat))
                    .addGroup(panel_sc_modif_supprLayout.createSequentialGroup()
                        .addComponent(ms_sc_lbl_cat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ms_sc_cbb_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ms_sc_lbl_sous_cat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ms_sc_cbb_sous_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_sc_modif_supprLayout.setVerticalGroup(
            panel_sc_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_sc_modif_supprLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_sc_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ms_sc_lbl_cat)
                    .addComponent(ms_sc_cbb_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ms_sc_cbb_sous_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ms_sc_lbl_sous_cat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_sc_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_sc_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ms_sc_btn_supprimer_sous_cat)
                        .addComponent(ms_sc_btn_modifier_sous_cat))
                    .addGroup(panel_sc_modif_supprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ms_sc_lbl_nom_sous_cat1)
                        .addComponent(ms_sc_tf_nom_sous_cat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout onglet_categoriesLayout = new javax.swing.GroupLayout(onglet_categories);
        onglet_categories.setLayout(onglet_categoriesLayout);
        onglet_categoriesLayout.setHorizontalGroup(
            onglet_categoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_c_ajout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_c_modif_suppr, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
            .addComponent(panel_sc_ajout, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
            .addComponent(panel_sc_modif_suppr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        onglet_categoriesLayout.setVerticalGroup(
            onglet_categoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(onglet_categoriesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_c_ajout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_c_modif_suppr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_sc_ajout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_sc_modif_suppr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        tpanel_onglets.addTab("Catégories", onglet_categories);

        javax.swing.GroupLayout onglet_promotionsLayout = new javax.swing.GroupLayout(onglet_promotions);
        onglet_promotions.setLayout(onglet_promotionsLayout);
        onglet_promotionsLayout.setHorizontalGroup(
            onglet_promotionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 899, Short.MAX_VALUE)
        );
        onglet_promotionsLayout.setVerticalGroup(
            onglet_promotionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        tpanel_onglets.addTab("Promotions", onglet_promotions);

        javax.swing.GroupLayout onglet_clientsLayout = new javax.swing.GroupLayout(onglet_clients);
        onglet_clients.setLayout(onglet_clientsLayout);
        onglet_clientsLayout.setHorizontalGroup(
            onglet_clientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 899, Short.MAX_VALUE)
        );
        onglet_clientsLayout.setVerticalGroup(
            onglet_clientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        tpanel_onglets.addTab("Clients", onglet_clients);

        javax.swing.GroupLayout panel_generalLayout = new javax.swing.GroupLayout(panel_general);
        panel_general.setLayout(panel_generalLayout);
        panel_generalLayout.setHorizontalGroup(
            panel_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_generalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpanel_onglets)
                .addContainerGap())
        );
        panel_generalLayout.setVerticalGroup(
            panel_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_generalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpanel_onglets, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panel_general, java.awt.BorderLayout.CENTER);

        BarreMenu.setToolTipText("Test");

        fichier.setText("Fichier");

        gestionProduits.setText("Gestion Produits");
        gestionProduits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionProduitsActionPerformed(evt);
            }
        });
        fichier.add(gestionProduits);

        gestionCategories.setText("Gestion Catégories");
        gestionCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionCategoriesActionPerformed(evt);
            }
        });
        fichier.add(gestionCategories);

        gestionPromotions.setText("Gestion Promotions");
        gestionPromotions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionPromotionsActionPerformed(evt);
            }
        });
        fichier.add(gestionPromotions);

        gestionClients.setText("Gestion Clients");
        gestionClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionClientsActionPerformed(evt);
            }
        });
        fichier.add(gestionClients);

        charger.setText("Charger");
        fichier.add(charger);
        fichier.add(separatorGestionSave);

        sauvegarder.setText("Sauvegarder");
        fichier.add(sauvegarder);
        fichier.add(separatorSaveQuit);

        quitter.setText("Quitter");
        quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitterActionPerformed(evt);
            }
        });
        fichier.add(quitter);

        BarreMenu.add(fichier);

        aPropos.setText("A propos");

        version.setText("Version");
        version.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                versionActionPerformed(evt);
            }
        });
        aPropos.add(version);

        BarreMenu.add(aPropos);

        setJMenuBar(BarreMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents
           
    private void ms_c_btn_supprimer_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_c_btn_supprimer_catActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ms_c_btn_supprimer_catActionPerformed
   
    private void r_cbb_categorieItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_r_cbb_categorieItemStateChanged
        r_cbb_sous_cat.removeAllItems();
        String s = r_cbb_categorie.getSelectedItem().toString();
        List<String> listeSousCat = getSousCategories(s);

        for (String sousCat : listeSousCat) {
            r_cbb_sous_cat.addItem(sousCat);
        }    
        
    }//GEN-LAST:event_r_cbb_categorieItemStateChanged

    private void ams_cbb_categorieItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ams_cbb_categorieItemStateChanged
        ams_cbb_sous_cat.removeAllItems();
        String s = ams_cbb_categorie.getSelectedItem().toString();
        List<String> listeSousCat = getSousCategories(s);

        for (String sousCat : listeSousCat) {
            ams_cbb_sous_cat.addItem(sousCat);
        }
    }//GEN-LAST:event_ams_cbb_categorieItemStateChanged

    private void ms_sc_cbb_catItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ms_sc_cbb_catItemStateChanged
        ms_sc_cbb_sous_cat.removeAllItems();
        String s = ms_sc_cbb_cat.getSelectedItem().toString();
        List<String> listeSousCat = getSousCategories(s);

        for (String sousCat : listeSousCat) {
            ms_sc_cbb_sous_cat.addItem(sousCat);
        }
    }//GEN-LAST:event_ms_sc_cbb_catItemStateChanged

    private void r_btn_effacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_btn_effacerActionPerformed
                    int input = JOptionPane.showConfirmDialog(null, "Voulez-vous reinitialiser les champs ?", "Confirmation",JOptionPane.YES_NO_OPTION);
                    if (input == JOptionPane.YES_OPTION) {
                        r_tf_nom_produit.setText("");
                        r_cbb_categorie.setSelectedIndex(0);                        
                    }
    }//GEN-LAST:event_r_btn_effacerActionPerformed

    private void ams_btn_effacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ams_btn_effacerActionPerformed
                    int input = JOptionPane.showConfirmDialog(null, "Voulez-vous reinitialiser les champs ?", "Confirmation",JOptionPane.YES_NO_OPTION);
                    if (input == JOptionPane.YES_OPTION) {
                        ams_tf_id_produit.setText("");
                        ams_cbb_categorie.setSelectedIndex(0);            
                        ams_tf_nom_produit.setText("");
                        ams_ta_description.setText("");
                        ams_tf_prix.setText("");
                        ams_btngrp_en_promotion.clearSelection();
                        ams_rdobtn_non.setSelected(true);
                        ams_tf_taux_promo.setText("");
                        ams_tf_prix_reduit.setText("");
                        ams_tf_stock.setText("");
                    }
    }//GEN-LAST:event_ams_btn_effacerActionPerformed

    private void quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitterActionPerformed
        int input = JOptionPane.showConfirmDialog(null, "Etes-vous d'accord pour quitter ?", "Confirmation",JOptionPane.YES_NO_OPTION);
        if (input == JOptionPane.YES_OPTION) {
            System.exit(0);
        }         
    }//GEN-LAST:event_quitterActionPerformed

    private void gestionCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionCategoriesActionPerformed
        tpanel_onglets.setSelectedComponent(onglet_categories);
    }//GEN-LAST:event_gestionCategoriesActionPerformed

    private void gestionProduitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionProduitsActionPerformed
        tpanel_onglets.setSelectedComponent(onglet_produits);
    }//GEN-LAST:event_gestionProduitsActionPerformed

    private void gestionPromotionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionPromotionsActionPerformed
        tpanel_onglets.setSelectedComponent(onglet_promotions);
    }//GEN-LAST:event_gestionPromotionsActionPerformed

    private void gestionClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionClientsActionPerformed
        tpanel_onglets.setSelectedComponent(onglet_clients);
    }//GEN-LAST:event_gestionClientsActionPerformed

    private void versionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_versionActionPerformed
         JOptionPane.showMessageDialog(null, ("""
                                              Auteurs : Jerome Bonard - Yoann Cathelain  - Nathan Podlejski
                                              
                                              Gestion catalogue V2"""), "Version", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_versionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarreMenu;
    private javax.swing.JMenu aPropos;
    private javax.swing.JButton a_c_btn_ajouter_cat;
    private javax.swing.JLabel a_c_lbl_nom_cat;
    private javax.swing.JTextField a_c_tf_nom_cat;
    private javax.swing.JButton a_sc_btn_ajouter_sous_cat;
    private javax.swing.JComboBox<String> a_sc_cbb_cat;
    private javax.swing.JLabel a_sc_lbl_cat;
    private javax.swing.JLabel a_sc_lbl_nom_sous_cat;
    private javax.swing.JTextField a_sc_tf_nom_sous_cat;
    private javax.swing.JButton ams_btn_ajouter_produit;
    private javax.swing.JButton ams_btn_effacer;
    private javax.swing.JButton ams_btn_modifier_produit;
    private javax.swing.JButton ams_btn_supprimer_produit;
    private javax.swing.ButtonGroup ams_btngrp_en_promotion;
    private javax.swing.JComboBox<String> ams_cbb_categorie;
    private javax.swing.JComboBox<String> ams_cbb_sous_cat;
    private javax.swing.JLabel ams_lbl_description;
    private javax.swing.JLabel ams_lbl_en_promotion;
    private javax.swing.JLabel ams_lbl_id_produit;
    private javax.swing.JLabel ams_lbl_nom_produit;
    private javax.swing.JLabel ams_lbl_prix;
    private javax.swing.JLabel ams_lbl_prix_reduit;
    private javax.swing.JLabel ams_lbl_stock;
    private javax.swing.JLabel ams_lbl_taux_promo;
    private javax.swing.JLabel ams_p_lbl_categorie;
    private javax.swing.JLabel ams_p_lbl_sous_cat;
    private javax.swing.JRadioButton ams_rdobtn_non;
    private javax.swing.JRadioButton ams_rdobtn_oui;
    private javax.swing.JScrollPane ams_scroll_description;
    private javax.swing.JTextArea ams_ta_description;
    private javax.swing.JTextField ams_tf_id_produit;
    private javax.swing.JTextField ams_tf_nom_produit;
    private javax.swing.JTextField ams_tf_prix;
    private javax.swing.JTextField ams_tf_prix_reduit;
    private javax.swing.JTextField ams_tf_stock;
    private javax.swing.JTextField ams_tf_taux_promo;
    private javax.swing.JMenuItem charger;
    private javax.swing.JMenu fichier;
    private javax.swing.JMenuItem gestionCategories;
    private javax.swing.JMenuItem gestionClients;
    private javax.swing.JMenuItem gestionProduits;
    private javax.swing.JMenuItem gestionPromotions;
    private javax.swing.JButton ms_c_btn_modifier_cat;
    private javax.swing.JButton ms_c_btn_supprimer_cat;
    private javax.swing.JComboBox<String> ms_c_cbb_categorie;
    private javax.swing.JLabel ms_c_lbl_categorie;
    private javax.swing.JLabel ms_c_lbl_nom_cat;
    private javax.swing.JTextField ms_c_tf_nom_cat;
    private javax.swing.JButton ms_sc_btn_modifier_sous_cat;
    private javax.swing.JButton ms_sc_btn_supprimer_sous_cat;
    private javax.swing.JComboBox<String> ms_sc_cbb_cat;
    private javax.swing.JComboBox<String> ms_sc_cbb_sous_cat;
    private javax.swing.JLabel ms_sc_lbl_cat;
    private javax.swing.JLabel ms_sc_lbl_nom_sous_cat1;
    private javax.swing.JLabel ms_sc_lbl_sous_cat;
    private javax.swing.JTextField ms_sc_tf_nom_sous_cat1;
    private javax.swing.JPanel onglet_categories;
    private javax.swing.JPanel onglet_clients;
    private javax.swing.JPanel onglet_produits;
    private javax.swing.JPanel onglet_promotions;
    private javax.swing.JPanel panel_c_ajout;
    private javax.swing.JPanel panel_c_modif_suppr;
    private javax.swing.JPanel panel_general;
    private javax.swing.JPanel panel_p_ajout_modif_suppr;
    private javax.swing.JPanel panel_recherche;
    private javax.swing.JPanel panel_sc_ajout;
    private javax.swing.JPanel panel_sc_modif_suppr;
    private javax.swing.JMenuItem quitter;
    private javax.swing.JButton r_btn_effacer;
    private javax.swing.JButton r_btn_rechercher;
    private javax.swing.JComboBox<String> r_cbb_categorie;
    private javax.swing.JComboBox<String> r_cbb_sous_cat;
    private javax.swing.JLabel r_lbl_categorie;
    private javax.swing.JLabel r_lbl_nom_produit;
    private javax.swing.JLabel r_lbl_sous_cat;
    private javax.swing.JTextField r_tf_nom_produit;
    private javax.swing.JMenuItem sauvegarder;
    private javax.swing.JPopupMenu.Separator separatorGestionSave;
    private javax.swing.JPopupMenu.Separator separatorSaveQuit;
    private javax.swing.JTabbedPane tpanel_onglets;
    private javax.swing.JMenuItem version;
    // End of variables declaration//GEN-END:variables
}
